### ISSUE TITLE
Terminology: threads -> processes

### ISSUE THREAD

**Issue by HenrikBengtsson** [kadyb/stars-parallel#1]
Hello. I'd like to suggest to use the term "process" instead of "thread" throughout, e.g. multi-process instead of multi-thread.

The term thread means a different thing than process. All parallelization done at the R level uses processes. Parallelization via threads are only available via C code.

**Comment by kadyb** [comment]
Thank you very much and I appreciate you reading my tutorial as you are expert in parallelization.

This should be improved by f930f03.
